### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by suryacaprice** [text-machine-lab/CliNER#15]
python cliner predict --txt data/examples/ex_doc.txt --out data/predictions --model models/silver.crf --format i2b2
Traceback (most recent call last):
  File "cliner", line 60, in <module>
    main()
  File "cliner", line 52, in main
    predict.main()
  File "/home/caprice/serverless-nodejs-app/CliNER/code/predict.py", line 79, in main
    predict(files, args.model, args.output, format=format)
  File "/home/caprice/serverless-nodejs-app/CliNER/code/predict.py", line 96, in predict
    model = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf4 in position 6: ordinal not in range(128

**Comment by SoRr0wW** [comment]
Try running it with Python 2.7
Had a similar Error with Python3
