### ISSUE TITLE
vector2.txt in LSTM_parameters.txt is not found

### ISSUE THREAD

**Issue by yzhaoinuw** [text-machine-lab/CliNER#18]
When training with LSTM, I got the following error:
`(base) yue@tredgar:~/python_projects/CliNER$ python cliner train --txt data/i2b2_txt --annotations data/i2b2_concept --format i2b2 --model models/i2b2_lstm.model --use-lstm
NO DEV
IN ERROR CHECK
0.1
	Creating 90/10 train/dev split
	vectorizing words all
TESTING NEW DATSET OBJECT
Load dataset... 

Traceback (most recent call last):
  File "cliner", line 60, in <module>
    main()
  File "cliner", line 49, in main
    train.main()
  File "/home/yue/python_projects/CliNER/code/train.py", line 158, in main
    train(training_list, args.model, args.format, args.use_lstm, logfile=args.log, val=val_list, test=test_list)
  File "/home/yue/python_projects/CliNER/code/train.py", line 194, in train
    model.train(train_docs, val=val_docs, test=test_docs)
  File "/home/yue/python_projects/CliNER/code/model.py", line 199, in train
    test_sents=test_sents, test_labels=test_labels)
  File "/home/yue/python_projects/CliNER/code/model.py", line 253, in train_fit
    dev_split=dev_split     )
  File "/home/yue/python_projects/CliNER/code/model.py", line 410, in generic_train
    dataset.load_dataset(Datasets_tokens,Datasets_labels,"",parameters)
  File "/home/yue/python_projects/CliNER/code/DatasetCliner_experimental.py", line 210, in load_dataset
    token_to_vector = hd.load_pretrained_token_embeddings(parameters)
  File "/home/yue/python_projects/CliNER/code/helper_dataset.py", line 210, in load_pretrained_token_embeddings
    file_input = codecs.open(parameters['token_pretrained_embedding_filepath'], 'r', 'UTF-8')
  File "/home/yue/anaconda3/lib/python3.7/codecs.py", line 898, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'vectors2.txt'
`
It seems that in LSTM_parameters.txt, the vectors2.txt on the first line is missing. Is this supposed to be the GloVe vectors?

**Comment by yzhaoinuw** [comment]
I used the pretrained GloVe vectors file from http://neuroner.com/data/word_vectors/glove.6B.100d.zip, as mentioned in the CliNER paper. This seems to be the vectors2.txt.

**Comment by Ketki-Savle** [comment]
Hi, 

For some reason, my cliner train command is not able to read DatasetCliner_experimental.py and this is giving me another error that Exp is not recognized. Could you please help me. Thanks.

**Comment by tnaumann** [comment]
Closing issues prior to archive.
