### ISSUE TITLE
Cliner Training foo.model issue

### ISSUE THREAD

**Issue by jdjmoon** [text-machine-lab/CliNER#30]
Hello, I have been trying to run the example in Google Colab and am having trouble with making foo.model with this code that is provided.

python cliner train --txt data/examples/ex_doc.txt --annotations data/examples/ex_doc.con --format i2b2 --model models/foo.model

When I run this, I got the following message:
NO DEV
	Creating 90/10 train/dev split
	vectorizing words all
	training classifiers all
Traceback (most recent call last):
  File "cliner", line 60, in <module>
    main()
  File "cliner", line 49, in main
    train.main()
  File "/content/gdrive/My Drive/Colab Notebooks/CliNER/code/train.py", line 155, in main
    train(training_list, args.model, args.format, args.use_lstm, logfile=args.log, val=val_list, test=test_list)
  File "/content/gdrive/My Drive/Colab Notebooks/CliNER/code/train.py", line 187, in train
    model.train(train_docs, val=val_docs, test=test_docs)
  File "/content/gdrive/My Drive/Colab Notebooks/CliNER/code/model.py", line 199, in train
    test_sents=test_sents, test_labels=test_labels)
  File "/content/gdrive/My Drive/Colab Notebooks/CliNER/code/model.py", line 230, in train_fit
    dev_split=dev_split     )
  File "/content/gdrive/My Drive/Colab Notebooks/CliNER/code/model.py", line 584, in generic_train
    test_X=test_X, test_Y=test_Y)
  File "/content/gdrive/My Drive/Colab Notebooks/CliNER/code/machine_learning/crf.py", line 149, in train
    train_pred = predict(model,     X)
  File "/content/gdrive/My Drive/Colab Notebooks/CliNER/code/machine_learning/crf.py", line 181, in predict
    clf_byte = bytearray(clf, 'latin1')
TypeError: encoding or errors without a string argument

How do I fix this? Thank you

**Comment by tnaumann** [comment]
Closing issues prior to archive, but adding a note which may be of help. Based on the error, this is likely an issue with text encoding (e.g. `bytes` vs `str`). It may require changing the encoding (currently `latin1`).
